# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieList
  pod 'MBProgressHUD'
  pod 'AFNetworking'

  target 'MovieListTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mockingjay'
  end

  target 'MovieListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
